#!/bin/bash

CIPHER='-aes-256-cbc -salt'
DATAFILE=${1:-"$(dirname $0)/data"}

trap 'exit 1' SIGHUP SIGINT SIGTERM

RC=1
while [[ RC -ne 0 ]]; do
    OUTPUT=$(openssl enc -d $CIPHER -salt -in "$DATAFILE")
    RC=$?
done

cat <<< "$OUTPUT"
